### ISSUE TITLE
[Feature Request] C# Bindings

### ISSUE THREAD

**Issue by douglasg14b** [Auburn/FastNoise2#32]
As the title says, C# bindings!

I would love to use this library in C#, and I'm sure it would attract attention from Unity devs as well. I have no experience with C++, and honestly didn't make much progress in attempting this myself. Somewhat compounded by some of the methods being a bit obtuse without describing comments (For me anyways).

Hopefully this isn't too large of an ask.

**Comment by Auburn** [comment]
Hi, I've had this request from a few people. Getting it working for "Encoded Node Trees" should be reasonably easy, since it doesn't require exposing all the node type classes. Instead of exposing all the node classes individually it probably makes more sense to expose the node type metadata, would mean the dll interface wouldn't need updating when new node types are added.

I'll probably start looking at it over the next week or so, well at least the C interface DLL, but from that it should be easy to create a C# wrapper

**Comment by douglasg14b** [comment]
That's great to hear!

**Comment by Auburn** [comment]
I've added DLL support to the FastNoise API and a C interface, that should let you call the functions from C#. Currently the C interface only has support for creating nodes from encoded node trees, I will look at adding direct node creation later. 

The C interface is in FastNoise_C.h

Here are the binaries from the latest CI build, I will make a new release that has them soon too.

[Win64-MSVC (9).zip](https://github.com/Auburn/FastNoise2/files/6259057/Win64-MSVC.9.zip)

**Comment by Auburn** [comment]
https://github.com/Auburn/FastNoise2Bindings

**Comment by douglasg14b** [comment]
@Auburn  Thanks! I really appreciate that ^_^

Just now circling back around to the process of switching from my own noise generation to this.
